In [9]:
import numpy as np

In [10]:
A = np.arange(6).reshape(3,2)
B = np.arange(8).reshape(2,4)

In [12]:
mul = np.dot(A, B)

In [13]:
print(mul)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [14]:
max = mul.max()

In [15]:
print(max)

47
